# Generated by Django 4.1 on 2022-09-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
